# Site settings
title: Gaston Sanchez
email:
description: > # this means to ignore newlines until "baseurl:"
  Gaston Sanchez website.
url: http://gastonsanchez.com
baseurl: /

# User setting
owner: Gaston Sanchez
email: "gaston.stat [at] gmail.com"
github_username: gastonstat
linkedin_username: sanchezgaston
address:
  - line: 309 Evans Hall
  - line: UC Berkeley, California
  # Feel free to add more lines here 
copyright: "Gaston Sanchez"

# API settings
google_api_key:

# Build settings
markdown: kramdown
highlighter: rouge
